<?php

namespace Jinya\Database\Attributes;

use Attribute;

#[Attribute(Attribute::TARGET_PROPERTY)]
readonly class Column
{
    public function __construct(
        public string $sqlName = '',
        public bool   $autogenerated = false,
        public bool   $unique = false,
        public mixed  $defaultValue = null,
    ) {
    }
}
