<?php

namespace Jinya\Database;

use DateTime;
use Jinya\Database\Attributes\Column;
use Jinya\Database\Attributes\Id;
use Jinya\Database\Attributes\Table;
use Jinya\Database\Converters\DateConverter;

#[Table('creatable_entity')]
class CreatableEntity implements Creatable
{
    use CreatableEntityTrait;

    #[Id]
    #[Column(autogenerated: true)]
    public int $id;

    #[Column]
    public string $name;

    #[Column(sqlName: 'display_name')]
    public ?string $displayName;

    #[Column(defaultValue: new DateTime('2021-05-01'))]
    #[DateConverter('Y-m-d H:i:s')]
    public ?DateTime $date;
}
