<?php

namespace Jinya\Database;

use DateTime;
use Jinya\Database\Attributes\Column;
use Jinya\Database\Attributes\Id;
use Jinya\Database\Attributes\Optional;
use Jinya\Database\Attributes\Table;

#[Table('creatable_entity')]
class CreatableEntity implements Creatable
{
    use CreatableEntityTrait;

    #[Id]
    #[Column(autogenerated: true)]
    public int $id;

    #[Column]
    public string $name;

    #[Column(sqlName: 'display_name')]
    #[Optional]
    public ?string $displayName;

    #[Column]
    #[DateConverter('Y-m-d H:i:s')]
    #[Optional(new DateTime('2021-05-01'))]
    public ?DateTime $date;
}
