<?php

namespace Jinya\Database;

use DateTime;
use Jinya\Database\Attributes\Column;
use Jinya\Database\Attributes\Id;
use Jinya\Database\Attributes\Table;

#[Table('findable_entity')]
class FindableEntity implements Findable
{
    use FindableEntityTrait;

    #[Id]
    #[Column(autogenerated: true)]
    public int $id;

    #[Column]
    public string $name;

    #[Column(sqlName: 'display_name')]
    public string $displayName;

    #[Column]
    public DateTime $date;
}
