<?php

namespace Jinya\Database\Cache;

use Jinya\Database\ValueConverter;

readonly class CacheColumn
{
    public function __construct(
        public string $propertyName = '',
        public string $sqlName = '',
        public ValueConverter|null $converter = null,
        public bool $autogenerated = false,
        public bool $notNull = true,
        public bool $unique = true,
        public mixed $defaultValue = false,
    ) {
    }
}
